FROM informaticsmatters/deep-app-ubuntu-1604:latest

COPY xchem_deep_score.py /root/train/fragalysis_test_files
RUN chmod 755 /root
RUN chmod 755 /root/train
RUN chmod 755 -R /root/train/fragalysis_test_files